export const listOfDogs = {
  42: "akita",
  41: "basset_hound",
  27: "beagle",
  21: "bloodhound",
  8: "border_collie",
  20: "border_terrier",
  40: "borzoi",
  33: "boston_terrier",
  39: "boxer",
  9: "bull_terrier",
  30: "bullmastiff",
  32: "chow_chow",
  13: "cocker_spaniel",
  31: "dalmatian",
  23: "daschund",
  11: "doberman",
  29: "fox_terrier",
  5: "french_bulldog",
  12: "german_pinscher",
  17: "german_shepherd",
  28: "german_spaniel",
  26: "golden_retriever",
  19: "great_dane",
  4: "greyhound",
  22: "husky",
  18: "jack_russell_terrier",
  6: "king_charles_spaniel",
  10: "labrador",
  7: "lakeland_terrier",
  34: "newfoundland",
  25: "pitbull",
  15: "pomeranian",
  35: "poodle",
  43: "pug",
  38: "rottweiler",
  37: "samoyed",
  14: "scottish_terrier",
  36: "shiba_inu",
  3: "shih_tzu",
  2: "St._Bernard",
  1: "tibetan_mastiff",
  16: "west_highland_white_terrier",
  24: "yorkshire_terrier"
};

const listOfBreeds = [
  "akita",
  "basset_hound",
  "beagle",
  "bloodhound",
  "border_collie",
  "border_terrier",
  "borzoi",
  "boston_terrier",
  "boxer",
  "bull_terrier",
  "bullmastiff",
  "chow_chow",
  "cocker_spaniel",
  "dalmatian",
  "daschund",
  "doberman",
  "fox_terrier",
  "french_bulldog",
  "german_pinscher",
  "german_shepherd",
  "german_spaniel",
  "golden_retriever",
  "great_dane",
  "greyhound",
  "husky",
  "jack_russell_terrier",
  "king_charles_spaniel",
  "labrador",
  "lakeland_terrier",
  "newfoundland",
  "pitbull",
  "pomeranian",
  "poodle",
  "pug",
  "rottweiler",
  "samoyed",
  "scottish_terrier",
  "shiba_inu",
  "shih_tzu",
  "St._Bernard",
  "tibetan_mastiff",
  "west_highland_white_terrier",
  "yorkshire_terrier"
];
